/* -*- buffer-read-only: t -*-
 *
 *    overload.h
 *
 *    Copyright (C) 1997, 1998, 2000, 2001, 2005, 2006, 2007, 2011
 *    by Larry Wall and others
 *
 *    You may distribute under the terms of either the GNU General Public
 *    License or the Artistic License, as specified in the README file.
 *
 * !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 * This file is built by regen/overload.pl.
 * Any changes made here will be lost!
 */

enum {
    to_sv_amg,		/* 0x00 ${}      */
    to_av_amg,		/* 0x01 @{}      */
    to_hv_amg,		/* 0x02 %{}      */
    to_gv_amg,		/* 0x03 *{}      */
    to_cv_amg,		/* 0x04 &{}      */
    inc_amg,		/* 0x05 ++       */
    dec_amg,		/* 0x06 --       */
    bool__amg,		/* 0x07 bool     */
    numer_amg,		/* 0x08 0+       */
    string_amg,		/* 0x09 ""       */
    not_amg,		/* 0x0a !        */
    copy_amg,		/* 0x0b =        */
    abs_amg,		/* 0x0c abs      */
    neg_amg,		/* 0x0d neg      */
    iter_amg,		/* 0x0e <>       */
    int_amg,		/* 0x0f int      */
    lt_amg,		/* 0x10 <        */
    le_amg,		/* 0x11 <=       */
    gt_amg,		/* 0x12 >        */
    ge_amg,		/* 0x13 >=       */
    eq_amg,		/* 0x14 ==       */
    ne_amg,		/* 0x15 !=       */
    slt_amg,		/* 0x16 lt       */
    sle_amg,		/* 0x17 le       */
    sgt_amg,		/* 0x18 gt       */
    sge_amg,		/* 0x19 ge       */
    seq_amg,		/* 0x1a eq       */
    sne_amg,		/* 0x1b ne       */
    nomethod_amg,	/* 0x1c nomethod */
    add_amg,		/* 0x1d +        */
    add_ass_amg,	/* 0x1e +=       */
    subtr_amg,		/* 0x1f -        */
    subtr_ass_amg,	/* 0x20 -=       */
    mult_amg,		/* 0x21 *        */
    mult_ass_amg,	/* 0x22 *=       */
    div_amg,		/* 0x23 /        */
    div_ass_amg,	/* 0x24 /=       */
    modulo_amg,		/* 0x25 %        */
    modulo_ass_amg,	/* 0x26 %=       */
    pow_amg,		/* 0x27 **       */
    pow_ass_amg,	/* 0x28 **=      */
    lshift_amg,		/* 0x29 <<       */
    lshift_ass_amg,	/* 0x2a <<=      */
    rshift_amg,		/* 0x2b >>       */
    rshift_ass_amg,	/* 0x2c >>=      */
    band_amg,		/* 0x2d &        */
    band_ass_amg,	/* 0x2e &=       */
    sband_amg,		/* 0x2f &.       */
    sband_ass_amg,	/* 0x30 &.=      */
    bor_amg,		/* 0x31 |        */
    bor_ass_amg,	/* 0x32 |=       */
    sbor_amg,		/* 0x33 |.       */
    sbor_ass_amg,	/* 0x34 |.=      */
    bxor_amg,		/* 0x35 ^        */
    bxor_ass_amg,	/* 0x36 ^=       */
    sbxor_amg,		/* 0x37 ^.       */
    sbxor_ass_amg,	/* 0x38 ^.=      */
    ncmp_amg,		/* 0x39 <=>      */
    scmp_amg,		/* 0x3a cmp      */
    compl_amg,		/* 0x3b ~        */
    scompl_amg,		/* 0x3c ~.       */
    atan2_amg,		/* 0x3d atan2    */
    cos_amg,		/* 0x3e cos      */
    sin_amg,		/* 0x3f sin      */
    exp_amg,		/* 0x40 exp      */
    log_amg,		/* 0x41 log      */
    sqrt_amg,		/* 0x42 sqrt     */
    repeat_amg,		/* 0x43 x        */
    repeat_ass_amg,	/* 0x44 x=       */
    concat_amg,		/* 0x45 .        */
    concat_ass_amg,	/* 0x46 .=       */
    smart_amg,		/* 0x47 ~~       */
    ftest_amg,		/* 0x48 -X       */
    regexp_amg,		/* 0x49 qr       */
    max_amg_code
    /* Do not leave a trailing comma here.  C9X allows it, C89 doesn't. */
};

#define NofAMmeth max_amg_code


/* ex: set ro: */
