/* -*- buffer-read-only: t -*-
   !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
   This file is built by regen_perly.pl from perly.y.
   Any changes made here will be lost!
 */

#define PERL_BISON_VERSION  30003

#ifdef PERL_CORE
/* A Bison parser, made by GNU Bison 3.3.  */

/* Bison interface for Yacc-like parsers in C

   Copyright (C) 1984, 1989-1990, 2000-2015, 2018-2019 Free Software Foundation,
   Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.

   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

/* Undocumented macros, especially those whose name start with YY_,
   are private implementation details.  Do not rely on them.  */

/* Debug traces.  */
#ifndef YYDEBUG
# define YYDEBUG 0
#endif
#if YYDEBUG
extern int yydebug;
#endif

/* Token type.  */
#ifndef YYTOKENTYPE
# define YYTOKENTYPE
  enum yytokentype
  {
    GRAMPROG = 258,
    GRAMEXPR = 259,
    GRAMBLOCK = 260,
    GRAMBARESTMT = 261,
    GRAMFULLSTMT = 262,
    GRAMSTMTSEQ = 263,
    GRAMSUBSIGNATURE = 264,
    PERLY_AMPERSAND = 265,
    PERLY_BRACE_OPEN = 266,
    PERLY_BRACE_CLOSE = 267,
    PERLY_BRACKET_OPEN = 268,
    PERLY_BRACKET_CLOSE = 269,
    PERLY_COMMA = 270,
    PERLY_DOLLAR = 271,
    PERLY_DOT = 272,
    PERLY_EQUAL_SIGN = 273,
    PERLY_MINUS = 274,
    PERLY_PERCENT_SIGN = 275,
    PERLY_PLUS = 276,
    PERLY_SEMICOLON = 277,
    PERLY_SLASH = 278,
    PERLY_SNAIL = 279,
    PERLY_STAR = 280,
    KW_FORMAT = 281,
    KW_PACKAGE = 282,
    KW_CLASS = 283,
    KW_LOCAL = 284,
    KW_MY = 285,
    KW_IF = 286,
    KW_ELSE = 287,
    KW_ELSIF = 288,
    KW_UNLESS = 289,
    KW_FOR = 290,
    KW_UNTIL = 291,
    KW_WHILE = 292,
    KW_CONTINUE = 293,
    KW_GIVEN = 294,
    KW_WHEN = 295,
    KW_DEFAULT = 296,
    KW_TRY = 297,
    KW_CATCH = 298,
    KW_FINALLY = 299,
    KW_DEFER = 300,
    KW_REQUIRE = 301,
    KW_DO = 302,
    KW_USE_or_NO = 303,
    KW_SUB_named = 304,
    KW_SUB_named_sig = 305,
    KW_SUB_anon = 306,
    KW_SUB_anon_sig = 307,
    BAREWORD = 308,
    METHCALL0 = 309,
    METHCALL = 310,
    THING = 311,
    PMFUNC = 312,
    PRIVATEREF = 313,
    QWLIST = 314,
    FUNC0OP = 315,
    FUNC0SUB = 316,
    UNIOPSUB = 317,
    LSTOPSUB = 318,
    PLUGEXPR = 319,
    PLUGSTMT = 320,
    LABEL = 321,
    LOOPEX = 322,
    DOTDOT = 323,
    YADAYADA = 324,
    FUNC0 = 325,
    FUNC1 = 326,
    FUNC = 327,
    UNIOP = 328,
    LSTOP = 329,
    MULOP = 330,
    ADDOP = 331,
    DOLSHARP = 332,
    HASHBRACK = 333,
    NOAMP = 334,
    COLONATTR = 335,
    FORMLBRACK = 336,
    FORMRBRACK = 337,
    SUBLEXSTART = 338,
    SUBLEXEND = 339,
    PREC_LOW = 340,
    OROP = 341,
    ANDOP = 342,
    NOTOP = 343,
    ASSIGNOP = 344,
    PERLY_QUESTION_MARK = 345,
    PERLY_COLON = 346,
    OROR = 347,
    DORDOR = 348,
    ANDAND = 349,
    BITOROP = 350,
    BITANDOP = 351,
    CHEQOP = 352,
    NCEQOP = 353,
    CHRELOP = 354,
    NCRELOP = 355,
    SHIFTOP = 356,
    MATCHOP = 357,
    PERLY_EXCLAMATION_MARK = 358,
    PERLY_TILDE = 359,
    UMINUS = 360,
    REFGEN = 361,
    POWOP = 362,
    PREINC = 363,
    PREDEC = 364,
    POSTINC = 365,
    POSTDEC = 366,
    POSTJOIN = 367,
    ARROW = 368,
    PERLY_PAREN_CLOSE = 369,
    PERLY_PAREN_OPEN = 370
  };
#endif

/* Value type.  */
#ifdef PERL_IN_TOKE_C
static bool
S_is_opval_token(int type) {
    switch (type) {
    case BAREWORD:
    case FUNC0OP:
    case FUNC0SUB:
    case LABEL:
    case LSTOPSUB:
    case METHCALL:
    case METHCALL0:
    case PLUGEXPR:
    case PLUGSTMT:
    case PMFUNC:
    case PRIVATEREF:
    case QWLIST:
    case THING:
    case UNIOPSUB:
	return 1;
    }
    return 0;
}
#endif /* PERL_IN_TOKE_C */
#endif /* PERL_CORE */
#if ! defined YYSTYPE && ! defined YYSTYPE_IS_DECLARED

union YYSTYPE
{

    I32	ival; /* __DEFAULT__ (marker for regen_perly.pl;
				must always be 1st union member) */
    char *pval;
    OP *opval;
    GV *gvval;

};

typedef union YYSTYPE YYSTYPE;
# define YYSTYPE_IS_TRIVIAL 1
# define YYSTYPE_IS_DECLARED 1
#endif



int yyparse (void);


/* Generated from:
 * 7fff5c86aebf1c7ae3e18ee7e03f6b539ad101778f946ff2123b50bfa9a451a6 perly.y
 * acf1cbfd2545faeaaa58b1cf0cf9d7f98b5be0752eb7a54528ef904a9e2e1ca7 regen_perly.pl
 * ex: set ro: */
